### ISSUE TITLE
I hope that KAJU can support different versions of the unzip file position. Now I don't know much about the CLI for development. https://github.com/ktekinay/Kaju Look at the image I edited.I hope someone can understand what I mean. Thank you

### ISSUE THREAD

**Issue by ilovebamboo** [ktekinay/Kaju#11]
I hope that KAJU can support different versions of the unzip file position. Now I don't know much about the CLI for development.
https://github.com/ktekinay/Kaju
Look at the image I edited.I hope someone can understand what I mean. Thank you
![qq20171029-091849](https://user-images.githubusercontent.com/6214084/32140683-a322be9e-bc37-11e7-9d06-34b10c0f89dd.jpg)

**Comment by ktekinay** [comment]
I don't expect to do this, but since it's open-source, feel free to submit a pull request.
