### ISSUE TITLE
Duplicated Event Definitions

### ISSUE THREAD

**Issue by JuliaTruchsess** [ktekinay/Kaju#12]
Following the step-by-step, I've copied the Kaju Classes folder into my project. When I compile I get the following errors:

KajuUpdateWindow.hsSocket.ReceiveProgress Declaration
hsSocket on KajuUpdateWindow implements the event "ReceiveProgress," but its superclass Kaju.HTTPSSocket has already implemented the event.
Sub ReceiveProgress(bytesReceived as integer, totalBytes as integer, newData as string)

KajuUpdateWindow.hsSocket.DownloadComplete Declaration
hsSocket on KajuUpdateWindow implements the event "DownloadComplete," but its superclass Kaju.HTTPSSocket has already implemented the event.
Sub DownloadComplete(url as string, httpStatus as integer, headers as internetHeaders, file as folderItem)

KajuUpdateWindow.hsSocket.Error Declaration
hsSocket on KajuUpdateWindow implements the event "Error," but its superclass Kaju.HTTPSSocket has already implemented the event.
Sub Error(code as integer)

KajuUpdateWindow.shZipper.DecompressCompleted Declaration
shZipper on KajuUpdateWindow implements the event "DecompressCompleted," but its superclass Kaju.ZipShell has already implemented the event.
Sub DecompressCompleted(zipFile As FolderItem, containingFolder As FolderItem)

KajuUpdateWindow.shZipper.Error Declaration
shZipper on KajuUpdateWindow implements the event "Error," but its superclass Kaju.ZipShell has already implemented the event.
Sub Error()

**Comment by ktekinay** [comment]
It sounds like you dragged the raw files/folders into your project rather than opening one of the Kaju projects to copy-and-paste them into your project. Could that be it?

**Comment by JuliaTruchsess** [comment]
Yes, indeed, that could be it! lol. Now I feel really stupid. But when I saw the word "folder" in "Copy the Kaju Classes folder into your project" I did not think of a Xojo "folder", I thought of a Finder folder. Maybe that could be made a little more explicit in the docs, e.g.: "In the IDE, copy the Kaju Classes folder from an example project into your project. " Thanks :)
