### ISSUE TITLE
Kaju Admin crashes if you move the save file while open

### ISSUE THREAD

**Issue by devtimi** [ktekinay/Kaju#13]
Title covers it. Haven't had a chance to look into the real reason, or what the best way to fix it would be. I thought it should be noted until someone has time to look.

**Comment by ktekinay** [comment]
"Doctor, doctor, it hurts when I do this." "Don't do that then."

:-)

Thanks for the report.

**Comment by ktekinay** [comment]
FYI, I can't reproduce this. If I save, move the file, then save again, a new file is created. Are you working off the version in the develop branch?

**Comment by devtimi** [comment]
The procedure was save, move file, return to Kaju Admin, crash. Something about updating the document in the titlebar on Window.Activate led down a rabbit hole to FolderItemAlias.Resolve which is where the crash occurred.

I am not able to reproduce the problem now that I'm looking into it. I did discover a weird issue though, after moving and returning to Kaju, save again and it re-creates the file in the old location. Hmm. Thoughts?

**Comment by ktekinay** [comment]
I changed the way the alias is handled for the next version and that, combined with the latest Xojo release, seems to fix the issues.

As a tip, you can't get SaveInfo before you actually, you know, save the file. :-)

**Comment by ktekinay** [comment]
Er, works on the Mac, not on Windows. I'm ok with that until Xojo gets it resolved.
