### ISSUE TITLE
Folder of the executable not correctly identified

### ISSUE THREAD

**Issue by NMgAeeyGqw** [ktekinay/Kaju#14]
Kaju Version 2.0 in DecompressCompleted the folder ReplacementAppFolder is not always correctly identified. In my case a subfolder "config" was selected resulting in the deletion of all the files.

This change in DecompressCompleted fixes the issue:

  for i as integer = 1 to containingFolder.Count
    dim f as FolderItem = containingFolder.Item( i )
    dim name as string = f.Name
    Dim leftChars As String = name.Left( 1 )
    If leftChars <> "." And leftChars <> "_" **And f.Directory=False** Then
      item = f
      Exit
    end if
  next

Arndt

**Comment by ktekinay** [comment]
I've integrated this fix into the next version, thanks.

**Comment by ktekinay** [comment]
Fixed in commit 68d588f2694d626577d876d052371facd93e4d17.

**Comment by ktekinay** [comment]
I stand corrected, this is a breaking change. What it is trying to identify here is a folder on both platforms, and there should only be one item in the folder it is checking. In fact, I changed it to make sure it IS a folder.

**Comment by NMgAeeyGqw** [comment]
Hello,

I guess your are right. My Zip-File had the wrong structure when I
suggested the change.
But I never got Kaju 2.0 to work correctly with Xojo 2019R3 on Windows 7.

Best Regards,

Arndt

Am Sa., 16. Mai 2020 um 00:07 Uhr schrieb Kem Tekinay <
notifications@github.com>:
