### ISSUE TITLE
Can't get it to work on Mac, ok on Windows

### ISSUE THREAD

**Issue by jmadren** [ktekinay/Kaju#17]
Just downloaded yesterday and set it up according to the instructions. First tried running the Admin app in Xojo 2019r3.1 and it wouldn't compile. Guessing it hasn't been updated for 2019r2+? Admin app runs fine in 2019r1.1.

It's not clear, but I assumed the URL configured for the UpdateChecker should point directly to the json file. But the instructions say in one place to "export the HTML data" and another "The update information that you will post will be a JSON file that is generated by the Admin app as an HTML file." However, the default filename of the Export function is "UpdateInformation.json". So I just used it as is and it seems to work fine. Might want to clarify that in the instructions.

So, I tried it in my app. The Windows version seems to be working fine, but the macOS version gives this error: "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." I'm not using a secure site for this test. I tried searching for that phrase and came up empty. This is on macOS 10.13, compiled with Xojo 2019r3.1.

On another matter, there are a couple of typos in the readme instructions, in the _ExecuteAsync vs. Execute_ section the second paragraph starts with "If yoru uddate information...".

**Comment by beatrixwillius** [comment]
On macOS every app that tries to connect to a server needs to add it to the plist file. Because my app downloads external resources from the internet I didn't have to do anything special.

[info.plist.zip](https://github.com/ktekinay/Kaju/files/4635606/info.plist.zip)

**Comment by ktekinay** [comment]
Thanks Jay, I was going to update the README today and I'll pay special attention to those points.

I don't know why you couldn't get the Admin app to run, but check the To_URLConnection branch. That's where you'll find the latest updates and I've been running it here with no issues. I plan to merge that into develop soon, and release shortly.

As Beatrix alluded, this is an issue that is documented in the LR under URLConnection. The required plist is included in the project files.

**Comment by jmadren** [comment]
Ah, ok! Thanks Beatrix, but the plist you provided wasn't complete. I used the one included in the project files as Kem suggested and it now works.

Kem, you may want to include this in the instructions as well, maybe also referencing the Xojo docs that address this issue: https://docs.xojo.com/UserGuide:App_Transport_Security

And sorry, I mis-remembered what the issue was with running the Admin app in 2019r3.1. It does compile, but when I try to save the file it produces an exception:

![Kaju Admin error](https://user-images.githubusercontent.com/22791228/82077239-14299700-96ad-11ea-9455-f7fa1cc9e485.png)

I downloaded the To_URLConnection branch and it won't compile (in either Xojo version), with the following errors:

![Kaju Admin compile errors](https://user-images.githubusercontent.com/22791228/82077358-476c2600-96ad-11ea-935e-cac358d1e9ca.png)

One more suggestion for the instructions: It was unclear to me how the Admin app saved information. The instructions state this under _Step By Step_: 

> Run the Kaju Admin app through the included project and save a new document with an appropriate name, something like "MyApp v.1.kaju".

So I thought it saved each version in the list as a separate file. Now I know they all are saved in one file, and the "v.1" in the example above is not warranted, and in fact is counter-intuitive.

Thanks again!

**Comment by ktekinay** [comment]
I'll put that comment into the README too.

Putting the version into the filename may be relevant, for example, you might want to distinguish the v1 updates from the v2 updates down the road. I'll make sure that's clear.

I just pushed a fix for that error, please pull and try again.

**Comment by jmadren** [comment]
Admin app compiles, runs and saves the file now using Xojo 2019r3.1.

Thanks for all your work on this project!

**Comment by ktekinay** [comment]
Will you be testing the update process itself in your app? If so, please let me know the results as I plan to merge, and release, these changes soon.

**Comment by jmadren** [comment]
I can, since I'm still in the testing phase of this release of my app.
Won't be until later today or tomorrow, though.

**Comment by ktekinay** [comment]
That's fine, I might merge today, but won't be releasing until next week anyway, just to be on the safe side.

Thanks.

**Comment by jmadren** [comment]
Kem, I have tried both my app and your test update app and can't get
either to work properly.

My app shows the update in the update window, and downloads it, but then
just seems to hang on "processing file". Same result on Mac and Windows,
except on Windows it shows a file copy progress after downloading, but
after that the update window is stuck just like the Mac version.

So I uploaded your test files to my server and compiled the test app. It
shows the four updates, but all four end with "The downloaded file appears
to be corrupted." I know the 1.2b2 version says that it is intentionally
corrupt, but are the other versions supposed to work correctly?

All of the above was with the To_URLConnection branch.

I also tried going back to the develop branch in my app but still got the
same results. So there may be two different issues here (or more). I am
working on adding several debugging measures to my app to better see what's
happening. Quick question, will this work in a debug run? I figured the app
needed to be built for the update to work properly, but it would be nice to
be able to stop through this with the debugger.

**Comment by ktekinay** [comment]
I don't know about the second issue, but I fixed the first yesterday afternoon. Please pull and try again.

**Comment by jmadren** [comment]
Still didn't work, but finally figured it out. The shZipper control was set
to Synchronous mode instead of Asynchronous, therefore the completed event
never fires. But get this - in the repository the control is set to
Asynchronous,
but when I copy the Kaju Classes folder from the Admin app, it changes
to Synchronous!
Probably another Xojo bug.

Anyway, I've got more testing to do, but at least now it's working!

I want to contribute something to this project, which is a recents system
for the Admin app (open recent files menu list). Are you open to that? If
so, should I commit to the To_URLConnection branch of my fork, or wait
until you merge back to the develop branch and commit there?

**Comment by ktekinay** [comment]
Sure, but I should warn you, I'm very picky about code. :-) 

Wait until I merge this into develop, then I'll start a new branch, submissions. You can commit against that.

For now, please keep the code API1 consistent. I'll switch over to API2 calls eventually, but I'd like to keep it somewhat backwards compatible.
