### ISSUE TITLE
Quit & Install

### ISSUE THREAD

**Issue by tcconway** [ktekinay/Kaju#9]
Hey there.

I think I have everything setup. But when I press the "Quit & Install" button on the updater window, my app quits and nothing else happens. I can see the correctly downloaded decompressed file within the TemporaryItems folder, it's just not being moved into place.

Any thoughts on where to debug?

Thanks!

OS: Mac
Versions: Xojo 2.1, Kaju (installed yesterday)

**Comment by ilovebamboo** [comment]
Yes, i have same question too.

**Comment by ktekinay** [comment]
Set App.UpdateInitiater to nil in App.Close, that should do it.
